/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=D:\test-ai\dev-env\google_keywords\.wrangler\typegen-config.jsonc --include-runtime=false --env-interface=CloudflareEnv D:\test-ai\dev-env\google_keywords\cloudflare-env.d.ts` (hash: df26939c7544f04fa762cd4d9517fb46)
interface __BaseEnv_CloudflareEnv {
	DB: D1Database;
	ASSETS: Fetcher;
	BENCHMARK_KEYWORD: "gpts";
	NEXT_PUBLIC_BENCHMARK_KEYWORD: "gpts";
	CACHE_EXPIRY_HOURS: "24";
	OPENROUTER_BASE_URL: "https://openrouter.ai/api/v1";
	OPENROUTER_MODEL: "openai/gpt-5.2";
	OPENROUTER_FILTER_TERMS: "赌博,博彩,赌场,投注,链接,新闻,名人,电影";
	OPENROUTER_SITE_URL: "";
	OPENROUTER_APP_NAME: "keyword-research";
	NEXT_PUBLIC_FILTER_TERMS: "gambling,betting,casino,news,celebrity,movie,film,lottery,博彩,赌博,赌场,投注,新闻,名人,电影";
	DEBUG_API_LOGS: "true";
	RESEARCH_STATUS_GET_EXECUTION_COMPAT: "true";
	BYOK_PROVIDER_CONNECTIONS_ENABLED: "false";
	BYOK_PROVIDER_CONNECTIONS_ALLOWLIST: "";
	BYOK_ACTIVE_KEK_VERSION: "v1";
	BYOK_KEK_READ_VERSIONS: "v1";
	BYOK_ACTIVE_FINGERPRINT_KEY_VERSION: "v1";
	BYOK_FINGERPRINT_KEY_READ_VERSIONS: "v1";
	SERP_LOCATION_NAME: "United States";
	SERP_LANGUAGE_CODE: "en";
	SERP_DEVICE: "desktop";
	SERP_OS: "windows";
	SERP_DEPTH: "10";
	NEXT_PUBLIC_APP_URL: "https://www.discoverkeywords.co";
	APP_URL: "https://www.discoverkeywords.co";
	D1_DATABASE_NAME: "ai-trends";
	WORKER_SELF_REFERENCE: Fetcher /* google-keywords */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BENCHMARK_KEYWORD" | "NEXT_PUBLIC_BENCHMARK_KEYWORD" | "CACHE_EXPIRY_HOURS" | "OPENROUTER_BASE_URL" | "OPENROUTER_MODEL" | "OPENROUTER_FILTER_TERMS" | "OPENROUTER_SITE_URL" | "OPENROUTER_APP_NAME" | "NEXT_PUBLIC_FILTER_TERMS" | "DEBUG_API_LOGS" | "RESEARCH_STATUS_GET_EXECUTION_COMPAT" | "BYOK_PROVIDER_CONNECTIONS_ENABLED" | "BYOK_PROVIDER_CONNECTIONS_ALLOWLIST" | "BYOK_ACTIVE_KEK_VERSION" | "BYOK_KEK_READ_VERSIONS" | "BYOK_ACTIVE_FINGERPRINT_KEY_VERSION" | "BYOK_FINGERPRINT_KEY_READ_VERSIONS" | "SERP_LOCATION_NAME" | "SERP_LANGUAGE_CODE" | "SERP_DEVICE" | "SERP_OS" | "SERP_DEPTH" | "NEXT_PUBLIC_APP_URL" | "APP_URL" | "D1_DATABASE_NAME">> {}
}
